### ISSUE TITLE
Provide some examples?

### ISSUE THREAD

**Issue by memoiry** [tawheeler/ForwardNets.jl#1]
Hi

Thanks for sharing this packages. Could you please provide one example to use the package? I think it would be better for others' understanding.

**Comment by tawheeler** [comment]
Disclaimer - this package isn't really meant for outside consumption.

You can construct your graph by pushing nodes to a `ForwardNet`.
Here we construct a net with 3 inputs, two hidden layers of 128 notes, and one output.

```
net = ForwardNet()
add_node!(net, Variable(:input, Array(Float32, 3)))
add_node!(net, Affine, :affine_1, indexof(net, :input), 128)
add_node!(net, ReLU(net[:affine_1].child), indexof(net, :affine_1))
add_node!(net, Affine, :affine_2, lastindex(net), 128)
add_node!(net, ReLU(net[:affine_2].child), indexof(net, :affine_2))
add_node!(net, Affine, :affine_3, lastindex(net), 1)
add_node!(net, Variable(:output, get_output(net[:affine_3])), indexof(net, :affine_3))
```

To run a forward pass you construct a `ForwardPass` object:
```
pass = calc_forwardpass(net, [:input], [:output])
```

The method `forward!` lets you execute the pass on the given inputs.
```
forward!(pass)
```

Note that you need to set the weights of each node appropriate and need to set the inputs values.

**Comment by memoiry** [comment]
Hi tawheeler

That's great. Thanks for quick response. Actually, I just want to use it for educational purpose, learn something from the source code. Thanks for sharing the code again!
